version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: stop-container.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: stop-container.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: start-container.sh
      timeout: 300
      runas: root
