version: 0.2

env:
  shell: bash
  variables:
    AWS_REGION: ap-south-1
    ECR_REPO: backend

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - IMAGE_TAG=$CODEBUILD_BUILD_NUMBER
      - echo "Image tag: $IMAGE_TAG"

  build:
    commands:
      - echo "Building backend Docker image..."
      - docker build -t $ECR_REPO:$IMAGE_TAG ecommerce-backend
      - docker tag $ECR_REPO:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing backend image to ECR..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
      - echo "Creating image.env for CodeDeploy..."
      - echo "IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG" > image.env
      - echo "Artifacts in root:"
      - ls -l .

artifacts:
  discard-paths: yes
  files:
    - appspec.yml
    - image.env
    - cicd/scripts/*.sh
